/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsialpha;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rezar_4
 */
public class FormScNew extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public FormScNew() {
        initComponents();
    }
    
    private void retrieve() {
        DefaultTableModel dm = new FormUpdaterSc().getData();
        jTable1.setModel(dm);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Kelamin", "Umur", "Negara", "Penyakit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Keluarkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Proses");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(update)
                        .addGap(221, 221, 221))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(update))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        retrieve();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int jumlahbaris = jTable1.getRowCount();
        int point=1;
        double informationloss=0;
        int pembagi = new FormUpdaterScNew().selectMaxUmur()-new FormUpdaterScNew().selectMinUmur();
        
        for(int i=0;i<jumlahbaris;i++){
            if((i+1) % 3==0 && i!=0){
                int id = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                String kelamin = "kelamin";
                int pbsatu;
                int pbdua;
                double ilneg;
                String umur;
                String negara;
                String negara1;
                String negara2;
                String negfix;
                
                int panjang_kode=jTable1.getValueAt(i, 3).toString().length();
                    if(i<=3){
                        umur = jTable1.getValueAt(i-2, 2).toString() + " - " + jTable1.getValueAt(i, 2).toString();
                    }else {
                        umur = jTable1.getValueAt(i-3, 2).toString() + " - " + jTable1.getValueAt(i, 2).toString();
                    }
                pbsatu = Integer.parseInt(jTable1.getValueAt(i, 2).toString())-Integer.parseInt(jTable1.getValueAt(i-2, 2).toString());
                pbdua = Integer.parseInt(jTable1.getValueAt(i-2, 2).toString());
                
                
                negara = jTable1.getValueAt(i, 3).toString();
                negara1 = jTable1.getValueAt(i-1, 3).toString();
                negara2 = jTable1.getValueAt(i-2, 3).toString();
                
                if(negara.equals(negara1) && negara.equals(negara2) && negara1.equals(negara2)){
                    negfix=negara;
                    ilneg = 0;
                }else { 
                    if(" United-States".equals(negara) || " Cuba".equals(negara) || " Mexico".equals(negara) || " Puerto-Rico".equals(negara)){
                        negara="america";
                    }else if(" India".equals(negara) || " South".equals(negara)){
                        negara="asia";
                    }

                    if(" United-States".equals(negara1) || " Cuba".equals(negara1) || " Mexico".equals(negara1) || " Puerto-Rico".equals(negara1)){
                        negara1="america";
                    }else if(" India".equals(negara1) || " South".equals(negara1)){
                        negara1="asia";
                    }

                    if(" United-States".equals(negara2) || " Cuba".equals(negara2) || " Mexico".equals(negara2) || " Puerto-Rico".equals(negara2)){
                        negara2="america";
                    }else if(" India".equals(negara2) || " South".equals(negara2)){
                        negara2="asia";
                    }

                    if(negara==negara1 && negara==negara2 && negara1==negara2){
                        negfix=negara;
                        ilneg = 0.6;
                    }else{
                        negfix="dunia";
                        ilneg = 1;
                     }
              }
                
                
                String penyakit = jTable1.getValueAt(i, 4).toString();
                informationloss = informationloss + (3*(pbsatu/pembagi + 1 + ilneg));
                
                

                System.out.print(" " +id+" ");
                System.out.print(" "+kelamin+" ");
                System.out.print(" "+ negfix + " ");
                System.out.print(" "+ umur + " ");
                System.out.print(" "+penyakit);
                System.out.print(" "+ informationloss + " ");
                System.out.println();        
            }
            
            
           
            //new BusUpdater().update(jTextField1.getText(), jTextField2.getText(), t, j)
            //new FormUpdater().update(id, kelamin, umur, kode_pos, penyakit);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        int jumlahBaris = jTable1.getRowCount();
        System.out.println(jumlahBaris);
        
        for(int u=1;u<=jumlahBaris;u++){
            if(jTable1.getValueAt(u-1, 3).toString().length()<6){
                new FormUpdater().updatekode(u,jTable1.getValueAt(u-1, 3).toString() + "0" );
            }
        }
        System.out.println(jTable1.getValueAt(0, 3).toString().length());
        
    }//GEN-LAST:event_updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
